--- 
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver-deployment
  namespace: development
  labels:
    app: timeteller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timeteller
  template:
    metadata:
      labels:
        app: timeteller
    spec:
      containers:
      - name: timeteller-container
        image: fh791/timeteller:latest
        ports:
        - containerPort: 80
      - name: rabbitmq-container
        image: rabbitmq:management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: rabbitmq
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbitmq
      ports:
        - containerPort: 15672
        - containerPort: 5671
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: timteller-service
  namespace: development
spec:
  selector:
    app: timeteller
  ports:
    - port: 80              # Application
      targetPort: 80
    - port: 15672           # RabbitMQ Management UI
      targetPort: 15672
  type: LoadBalancer
