--- 
apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeteller-deployment
  namespace: development
  labels:
    app: timeteller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timeteller
  template:
    metadata:
      labels:
        app: timeteller
    spec:
      containers:
      - name: timeteller-container
        image: fh791/timeteller:latest
        env:
        - name: RabbitMQ__HostName
          value: rabbitmq-service #.development.svc.cluster.local
        - name: RabbitMQ__UserName
          value: rabbitmq
        - name: RabbitMQ__Password
          value: rabbitmq
        ports:
        - name: application
          containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: development
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-container
        image: rabbitmq:management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: rabbitmq
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbitmq
        ports:
        - name: rabbitmq-ui
          containerPort: 15672
        - name: rabbitmq1
          containerPort: 5671
        - name: rabbitmq2
          containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: timeteller-service
  namespace: development
spec:
  selector:
    app: timeteller
  ports:
  - name: application-port
    port: 80
    targetPort: application
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: development
spec:
  selector:
    app: rabbitmq
  ports:
  - name: rabbitmq-ui-port
    port: 8080
    targetPort: rabbitmq-ui
  - name: rabbitmq1-port
    port: 5671
  - name: rabbitmq2-port
    port: 5672
  type: LoadBalancer